# Generated by Django 6.0.3 on 2026-03-22 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('folio', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombrePila', models.CharField(max_length=30)),
                ('primerApellido', models.CharField(max_length=30)),
                ('segundoApellido', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('folio', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='EdoCita',
            fields=[
                ('clave', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EdoHosp',
            fields=[
                ('clave', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=13, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EdoMasc',
            fields=[
                ('clave', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=13, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('clave', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('clave', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('folio', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=1)),
                ('fechaNacimiento', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color', models.CharField(max_length=30)),
                ('alergias', models.CharField(blank=True, max_length=100, null=True)),
                ('caracUnica', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.especie')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.edomasc')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('clave', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=90)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('folio', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombrePila', models.CharField(max_length=30)),
                ('primerApellido', models.CharField(max_length=30)),
                ('segundoApellido', models.CharField(blank=True, max_length=30, null=True)),
                ('dirCalle', models.CharField(max_length=30)),
                ('dirNum', models.CharField(max_length=10)),
                ('dirColonia', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('folio', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombrePila', models.CharField(max_length=30)),
                ('primerApellido', models.CharField(max_length=30)),
                ('segundoApellido', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('clave', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=13, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('sintomas', models.CharField(max_length=150)),
                ('frecCardiaca', models.IntegerField()),
                ('frecRespiratoria', models.IntegerField()),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observaciones', models.CharField(max_length=200)),
                ('diagnostico', models.CharField(max_length=150)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='web.cita')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.edocita'),
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('mascota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.mascota')),
                ('fechaApertura', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.mascota'),
        ),
        migrations.CreateModel(
            name='Hospitalizacion',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('diagnoIngreso', models.CharField(max_length=150)),
                ('fechaIngreso', models.DateField()),
                ('horaIngreso', models.TimeField()),
                ('obserGenerales', models.CharField(max_length=200)),
                ('fechaAlta', models.DateField(blank=True, null=True)),
                ('horaAlta', models.TimeField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.consulta')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.edohosp')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('pagoFinal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.consulta')),
                ('hospitalizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.hospitalizacion')),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.propietario'),
        ),
        migrations.AddField(
            model_name='cita',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.propietario'),
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('clave', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.especie')),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.raza'),
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('instruGenerales', models.CharField(max_length=150)),
                ('consulta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.consulta')),
                ('hospitalizacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.hospitalizacion')),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('frecCardiaca', models.IntegerField()),
                ('frecRespiratoria', models.IntegerField()),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hospitalizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.hospitalizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('clave', models.AutoField(primary_key=True, serialize=False)),
                ('numPrincipal', models.CharField(max_length=16, unique=True)),
                ('numSecundario', models.CharField(blank=True, max_length=16, null=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('folio', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombrePila', models.CharField(max_length=30)),
                ('primerApellido', models.CharField(max_length=30)),
                ('segundoApellido', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=16, unique=True)),
                ('cedula', models.CharField(max_length=8, unique=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
                ('administrador', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.administrador')),
                ('propietario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.propietario')),
                ('recepcionista', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.recepcionista')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.tipousuario')),
                ('veterinario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.veterinario')),
            ],
        ),
        migrations.AddField(
            model_name='hospitalizacion',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.veterinario'),
        ),
        migrations.AddField(
            model_name='cita',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.veterinario'),
        ),
        migrations.AddField(
            model_name='hospitalizacion',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.expediente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.expediente'),
        ),
        migrations.CreateModel(
            name='ServHosp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hospitalizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.hospitalizacion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.servicio')),
            ],
            options={
                'unique_together': {('servicio', 'hospitalizacion')},
            },
        ),
        migrations.CreateModel(
            name='ServCons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.consulta')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.servicio')),
            ],
            options={
                'unique_together': {('servicio', 'consulta')},
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('notas', models.CharField(max_length=50)),
                ('dosis', models.CharField(max_length=30)),
                ('frecuencia', models.CharField(max_length=30)),
                ('duracion', models.CharField(max_length=30)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.medicamento')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.receta')),
            ],
            options={
                'unique_together': {('receta', 'medicamento')},
            },
        ),
    ]
